### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by magic890** [mancuniancol/script.pulsar.ilcorsaronero-mc#1]
Here the stack trace:

        15:52:29 2259.677490 T:1419768864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
       - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
      Error Type: <type 'exceptions.TypeError'>
      Error Contents: translator() takes exactly 2 arguments (3 given)
      Traceback (most recent call last):
        File "/home/osmc/.kodi/addons/script.pulsar.ilcorsaronero-mc/main.py", line 74, in <module>
          provider.register(search, search_movie, search_episode)
        File "/home/osmc/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/provider.py", line 188, in register
          results = tuple(method(payload["search_object"]))
        File "/home/osmc/.kodi/addons/script.pulsar.ilcorsaronero-mc/main.py", line 59, in search_movie
          query = common.translator(info['imdb_id'], 'it', False)  # Just title
      TypeError: translator() takes exactly 2 arguments (3 given)
      -->End of Python script error report<--

**Comment by mancuniancol** [comment]
I didn't update this code with the latest version common.py.

Please, try again.
